name: optimal-control-diffusion
channels:
  - pytorch
  - nvidia
dependencies:
  - python=3.11
  - pytorch=2.5.1
  - torchvision=0.20.1
  - torchaudio=2.5.1
  - pytorch-cuda=12.4
  - pip
  - pip:
    - diffusers
    - xformers
    - transformers==4.49.0
    - accelerate==0.25.0
    - timm==0.4.12
    - decord
    - einops
    - scipy
    - pandas
    - coloredlogs
    - flatbuffers
    - numpy==1.26.4
    - packaging
    - protobuf
    - sympy
    - imageio-ffmpeg
    - insightface
    - facexlib
    - opencv-python-headless
    - gradio
    - onnxruntime-gpu